services:
  oxid_community.moduleinternals.module.fix.command:
    class: OxidCommunity\ModuleInternals\Command\ModuleFixCommand
    tags:
      - { name: 'console.command', command: 'module:fix', description: 'Fixes modules metadata states'}
